server:
  port: 7777
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: Major-Project-Cloud-API
  cloud:
    gateway:
      routes:
      - id: Major-Project-Admin-APP
        uri: http://localhost:7074/
        predicates:
        - Path=/case-worker/**
      - id: Major-Project-APP-Registartion
        predicates:
        - Path=/app-regi/**
        uri: http://localhost:7071/
      - id: Major-Project-Benfit-API
        predicates:
        - Path=/bi-send/**
        uri: http://localhost:7076/
      - id: Major-Project-Corresponding-API
        predicates:
        - Path=/co-triggers-api/**
        uri: http://localhost:7075/
      - id: Major-Project-Data-Collection-API
        predicates:
        - Path=/dc-api/**
        uri: http://localhost:7072/
      - id: Major-Project-Eligiblity-Determination-API
        predicates:
        - Path=/citizen-determination-api/**
        uri: http://localhost:7073/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
