spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: Major-Project-Eligiblity-Determination-API

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 7073
